### ISSUE TITLE
Add the FAQ section

### ISSUE THREAD

**Issue by ZooeyMiller** [iteles/learn-google-content-experiments#6]
As noted in the README already, we could add an FAQ section, initialised with a question of whether you should choose A/B testing or MVT testing. 

I'm currently doing research into what the use cases for each of these kinds of testing are, and will then update this readme with this information.

**Comment by ZooeyMiller** [comment]
Helpful resources: 
+ https://www.optimizely.com/optimization-glossary/multivariate-test-vs-ab-test/
+ the table in the learn-ab-and-multivariate-testing repo https://github.com/iteles/learn-ab-and-multivariate-testing

**Comment by iteles** [comment]
@ZooeyMiller Left a comment on this PR 👍

**Comment by ZooeyMiller** [comment]
As discussed in https://github.com/dwyl/learn-google-optimize/pull/7#discussion_r140474750 I will add a link to the learn-ab-and-multivariate-testing repo in an FAQ when https://github.com/iteles/learn-ab-and-multivariate-testing/issues/18 has been merged in.
