### ISSUE TITLE
Google content experiments to be deprecated

### ISSUE THREAD

**Issue by finnhodgkin** [iteles/learn-google-content-experiments#8]
I'm just creating an example a-b test so I can update the `setting up your experiment` section, but I noticed that Google recommend Optimize not Content Experiments:
 
![deprecation-warning](https://user-images.githubusercontent.com/22300773/30709747-2cf4b474-9efb-11e7-81a6-7069dbb5bbd4.gif)

**Comment by finnhodgkin** [comment]
Google Optimize is essentially just a nicer version of the old experiments api - nicer ui, easier required code snippets for each page, etc.

Also, as well as having the old redirect a/b tests, Optimize allows you to edit html/css within a page for smaller a/b tests.

Should I write a setup guide for Optimize instead of experiments? If so the repo name should probably be changed too.

**Comment by iteles** [comment]
@finnhodgkin Definitely! Some of what is here can be repurposed but we definitely want to go for what the latest one is.

**Comment by finnhodgkin** [comment]
@iteles I made a quick example Github pages a/b test on my profile because I don't have access to the control panel for this repo. Could you enable github pages for the master branch so I can move it here and write a quick setup guide to go with it? :blush: 

I'll start on the guide without the site in the meantime :+1:

**Comment by iteles** [comment]
@finnhodgkin Done! 
Moved to dwyl already so that we could avoid having to change the readme from `iteles.github.io` to `dwyl.github.io` at a later date 👍

**Comment by ZooeyMiller** [comment]
Working on adding the screenshots to the tutorial :sparkles:
